title: webdev-log
tagline: 
#author: dvkr
#  name: dvkr
#  email: your-email@domain.com
#description: > # this means to ignore newlines until "show_excerpts:"
#  where I document the freedoms and foibles of online learning in a webdev bootcamp,
#  through the lens of a former adult education instructor.
show_excerpts: true # set to true to show excerpts on the homepage
permalink: /:categories/:title/
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
# minima:
date_format: "%b %-d, %Y"
tags_path: /tags/
twitter_username: _dvkr

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

#remote_theme: 3dvkr/sziv2p.github.io
remote_theme: sziv2p/jekyll-theme-scaffold

feed:
  tags: true
  show_excerpts: true
  posts_limit: 5
  # most of this ^ is from https://github.com/jekyll/jekyll-feed/
#remote_theme: 3dvkr/minima
#theme: minima

#plugins:
# - jekyll-feed
# - jekyll-seo-tag

# theme: holo-alfa
#remote_theme: stijnvc/holo-alfa
#title: dvkr-log
#author: dvkr
#description: # > # this means to ignore newlines until "baseurl:"
#  where I document the freedoms and foibles of online learning in a webdev bootcamp

# social links
#twitter_username: _dvkr # DO NOT include the @ character, or else the build will fail!

#show_excerpts: true # set to false to remove excerpts on the homepage
