# theme: holo-alfa
remote_theme: stijnvc/holo-alfa
title: dvkr-log
author: dvkr
description: # > # this means to ignore newlines until "baseurl:"
  where I document the freedoms and foibles of online learning in a webdev bootcamp

# social links
twitter_username: _dvkr # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
